# Use the official Ruby image as the base image
FROM ruby:3.3.1

# Install essential dependencies
RUN apt-get update -qq && \
    apt-get install -y nodejs npm yarn postgresql-client

# Set the working directory in the container
WORKDIR /app

# Copy the Gemfile and Gemfile.lock into the container
COPY Gemfile Gemfile.lock ./

# Install gem dependencies
RUN bundle install

# Copy the package.json and yarn.lock into the container
COPY package.json yarn.lock ./

# Install JavaScript dependencies
RUN yarn install

# Copy the application code into the container
COPY . .

# Expose port 3000 to the Docker host
EXPOSE 3000

# Command to start the Rails server
CMD ["rails", "server"]
